env:
  es2020: true
  node: true
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/eslint-recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'prettier'
  - 'prettier/@typescript-eslint'
  - 'plugin:prettier/recommended'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 11
  sourceType: module
plugins:
  - '@typescript-eslint'
  - 'prettier'
rules: 
  prettier/prettier:
    - 'error'
    - printWidddth: 80 # 1行の折り返し長さ80
      tabWidth: 2
      semi: true
      singleQuote: true
      trailingComma: 'es5'
      bracketSpacing: true
      arrowParens: 'always'
  '@typescript-eslint/explicit-function-return-type': 'off'
  '@typescript-eslint/explicit-member-accessibility': 'off',
  '@typescript-eslint/indent': 'off',
  '@typescript-eslint/no-unnecessary-type-assertion': 'error',
  '@typescript-eslint/no-unused-vars': 'error',
  '@typescript-eslint/prefer-interface': 'off',
  'indent': 'off',

